services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nestjs
#     volumes:
#       - postgres-data:/var/lib/postgresql/data

# volumes:
#   postgres-data:

     